export const START_SCREEN_TITLE = `Welcome, Into the Digital World!`
export const START_NEW_GAME = `Novo jogo`
export const GAME_FILE_TITLE = `[NAME]`
export const GAME_FILE_TIME = `[TIME]`
export const LOAD_GAME = `Carregar jogo`
export const DELETE_GAME_FILE = `Excluir jogo`
export const THEMES_TITLE = `Tema`
export const SETTINGS_TITLE = `Configurações`
export const RETURN_TO_MAIN_SCREEN = `Voltar para a tela inicial`
