import type { GridType } from '@/Types/Grid.type'

import { floorTile } from '@/GameData/Zones/floor.tile'

export const grid: GridType = {
  1: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  2: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  3: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  4: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  5: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  6: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  7: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  8: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  9: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  10: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  11: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  12: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  13: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  14: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  15: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  16: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  17: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  18: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  },

  19: {
    1: { ...floorTile },
    2: { ...floorTile },
    3: { ...floorTile },
    4: { ...floorTile },
    5: { ...floorTile },
    6: { ...floorTile },
    7: { ...floorTile },
    8: { ...floorTile },
    9: { ...floorTile },
    10: { ...floorTile },
    11: { ...floorTile },
    12: { ...floorTile },
    13: { ...floorTile },
    14: { ...floorTile },
    15: { ...floorTile },
    16: { ...floorTile },
    17: { ...floorTile },
    18: { ...floorTile },
    19: { ...floorTile }
  }
}
