export const APPS_TITLE = `Installed apps`
export const APPS_SAVE = `Save Data`
export const APPS_LOGOFF = `Log Off`
export const APPS_ACHIEVEMENTS = `Achievements`
export const APPS_ACQUINTANCES = `Contacts`
export const APPS_JOURNAL = `Journal`
export const APPS_LOCATION = `Fast Travel`
export const APPS_PARTNERSLIST = `Encyclopedia`
export const APPS_RESEARCHESLIST = `Encyclopedia`
export const APPS_INVENTORY = `Inventory`
