export const ENCYCLOPEDIA_CATEGORY_INPARTY = `Current party:`
export const ENCYCLOPEDIA_CATEGORY_OTHERS = `Your other Digimons:`
export const ENCYCLOPEDIA_NO_OTHERS = `Try composing new Digimons!`
export const ENCYCLOPEDIA_FULL_PICTURE = `Full body picture:`
export const ENCYCLOPEDIA_DESCRIPTION = `General description`
export const ENCYCLOPEDIA_FAMILIES = `Families`
export const ENCYCLOPEDIA_ATTRIBUTE = `Attribute`
export const ENCYCLOPEDIA_STATS = `Stats`
export const ENCYCLOPEDIA_ATTACKS = `Moves`
export const ENCYCLOPEDIA_ATTACKS_DETAILS = `[NAME] - Cooldown: [COOLDOWN] turns`
export const ENCYCLOPEDIA_EQUIPMENTS = `Equipments`
export const ENCYCLOPEDIA_EQUIPMENTS_NOITEMS = `No item in this slot.`
export const ENCYCLOPEDIA_EQUIPMENTS_NOAVAILABLE = `No equipments available.`
export const ENCYCLOPEDIA_HEADER_PARTNERSLIST = `My Digimons`
export const ENCYCLOPEDIA_HEADER_RESEARCHESLIST = `My Researches`
export const ENCYCLOPEDIA_HEADER_ENCYCLOPEDIA = `Digimon Encyclopedia`
export const ENCYCLOPEDIA_STATS_VALUE = `[NAME]: [VALUE]`
export const ENCYCLOPEDIA_BOND = `Partner bond: [VALUE]`

export const MY_RESEARCHES_TITLE = `Researches done:`
export const MY_RESEARCHES_EMPTY = `Currently, you haven't researched no Digimon data. Talk to Nanomon in Root Domain to do so.`
export const MY_RESEARCHES_DETAILS_REQUIRED = `Required materials:`
export const MY_RESEARCHES_DETAILS_OPTIONAL = `Other materials:`
