import {
  RESEARCH_KOROMON_RECIPE_FULL,
  RESEARCH_KOROMON_RECIPE_CORE,
  RESEARCH_KOROMON_RECIPE_DR,
  RESEARCH_KOROMON_RECIPE_VB
} from './Koromon.data'
import { RESEARCH_TANEMON_RECIPE_FULL } from './Tanemon.data'

export {
  RESEARCH_KOROMON_RECIPE_FULL,
  RESEARCH_KOROMON_RECIPE_CORE,
  RESEARCH_KOROMON_RECIPE_DR,
  RESEARCH_KOROMON_RECIPE_VB,
  RESEARCH_TANEMON_RECIPE_FULL
}

export const ALL_RESEARCHES = [
  RESEARCH_KOROMON_RECIPE_FULL,
  RESEARCH_KOROMON_RECIPE_CORE,
  RESEARCH_KOROMON_RECIPE_DR,
  RESEARCH_KOROMON_RECIPE_VB,
  RESEARCH_TANEMON_RECIPE_FULL
]
