import {
  RESEARCH_KOROMON_RECIPE_FULL,
  RESEARCH_KOROMON_RECIPE_CORE,
  RESEARCH_KOROMON_RECIPE_DR,
  RESEARCH_KOROMON_RECIPE_VB
} from './Koromon.data'
import { RESEARCH_TUNOMON_RECIPE_FULL } from './Tunomon.data'
import { RESEARCH_MOCHIMON_RECIPE_FULL } from './Mochimon.data'
import { RESEARCH_PYOCOMON_RECIPE_FULL } from './Pyocomon.data'
import { RESEARCH_TANEMON_RECIPE_FULL } from './Tanemon.data'
import { RESEARCH_BUKAMON_RECIPE_FULL } from './Bukamon.data'
import { RESEARCH_TOKOMON_RECIPE_FULL } from './Tokomon.data'
import { RESEARCH_NYAROMON_RECIPE_FULL } from './Nyaromon.data'

export {
  RESEARCH_KOROMON_RECIPE_FULL,
  RESEARCH_KOROMON_RECIPE_CORE,
  RESEARCH_KOROMON_RECIPE_DR,
  RESEARCH_KOROMON_RECIPE_VB,
  RESEARCH_TUNOMON_RECIPE_FULL,
  RESEARCH_MOCHIMON_RECIPE_FULL,
  RESEARCH_PYOCOMON_RECIPE_FULL,
  RESEARCH_TANEMON_RECIPE_FULL,
  RESEARCH_BUKAMON_RECIPE_FULL,
  RESEARCH_TOKOMON_RECIPE_FULL,
  RESEARCH_NYAROMON_RECIPE_FULL
}

export const ALL_RESEARCHES = [
  RESEARCH_KOROMON_RECIPE_FULL,
  RESEARCH_KOROMON_RECIPE_CORE,
  RESEARCH_KOROMON_RECIPE_DR,
  RESEARCH_KOROMON_RECIPE_VB,

  RESEARCH_TUNOMON_RECIPE_FULL,
  RESEARCH_PYOCOMON_RECIPE_FULL,
  RESEARCH_TANEMON_RECIPE_FULL,
  RESEARCH_BUKAMON_RECIPE_FULL,
  RESEARCH_TOKOMON_RECIPE_FULL,
  RESEARCH_NYAROMON_RECIPE_FULL
]
